[project]
name = "star_utils"
authors = [
    {name = "Zane A. Gibbs", email = "zgibbs@health.ucsd.edu"},
    {name = "Ethan J Armand", email = "earmand@ucsd.edu" }
]
description = "Star Utils: A simple set of analysis and plotting utilities for starfish data"
requires-python = ">=3.9, <3.13"
dynamic = ["version"]
[tool.setuptools.packages.find]
where = ['star_utils']